sudo: required
services:
- docker
before_install:
- docker build -t hugovp/node-chat-app_test -f Dockerfile.dev .
script:
- docker run hugovp/node-chat-app_test npm run test -- --coverage
after_success:
  - docker build -t hugovp/node-chat-app .
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to Docker Hub
  - docker push hugovp/node-chat-app
  
# deploy:
#   provider: heroku
#   api_key:
#     secure: $HEROKU_AUTH_TOKEN
#   app: nameless-coast-48197
#   on:
#     repo: HugoVP/node-chat-app