version: "3"
services:
  api:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - /app/.git
      - /app/node_modules
      - ./:/app
    environment:
      - PORT=${PORT}
  api-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/.git
      - /app/node_modules
      - ./:/app
    command: ["npm", "run", "test-watch"]