version: "3"
services:
  api:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - PORT=${PORT}