version: "3"
services:
  api-playground:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./:/app
    command: ["npm", "run", "playground"]
    environment:
      - PLAYGROUND_FILE=${FILE}